{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ibm-portworx.fullname" . }}
  namespace: {{ include "ibm-portworx.namespace" . }}
  labels:
    {{- include "ibm-portworx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "list"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterrolebindings"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ibm-portworx.fullname" . }}
  namespace: {{ include "ibm-portworx.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
  labels:
  {{- include "ibm-portworx.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "daemonsets"
    verbs:
      - "list"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ibm-portworx.fullname" . }}
  namespace: {{ include "ibm-portworx.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
  labels:
  {{- include "ibm-portworx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ibm-portworx.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ibm-portworx.serviceAccountName" . }}
    namespace: {{ include "ibm-portworx.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ibm-portworx.fullname" . }}
  namespace: {{ include "ibm-portworx.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
  labels:
  {{- include "ibm-portworx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ibm-portworx.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ibm-portworx.serviceAccountName" . }}
    namespace: {{ include "ibm-portworx.namespace" . }}
{{- end -}}
