{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibm-portworx.serviceAccountName" . }}
  namespace: {{ include "ibm-portworx.namespace" . }}
  labels:
    {{- include "ibm-portworx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    helm.sh/hook-weight: "-5"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
