# Default values for ibm-cp4d-watson-studio-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: wa-cr

spec:
  license:
    accept: "true"
    license: Enterprise
  version: 4.0.8
  datastores:
    postgres:
      storageClassName: managed-nfs-storage
