# Default values for ibm-cp4d-analytics-engine-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: analyticsengine-sample

spec:
  license:
    accept: "true"
    license: Enterprise
  version: 4.0.4
  storageClass: managed-nfs-storage