apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "operator.name" . }}
  namespace: {{ include "operator.operator-namespace" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  channel: {{ include "operator.channel" . }}
  installPlanApproval: Automatic
  name: {{ include "operator.catalog-name" . }}
  source: {{ include "operator.source" . }}
  sourceNamespace: {{ include "operator.olm-namespace" . }}
  config:
    resources:
      limits:
        cpu: 400m
        memory: 700Mi
      requests:
        cpu: 400m
        memory: 40Mi
